### ISSUE TITLE
dpd on openshift

### ISSUE THREAD

**Issue by kosir** [ipepe/dpd-openshift-start-script#1]
I know it's not the right place to ask such questions, but maybe you know... Openshift free account is limited to 3 gears and cca. 15 concurrent connections (requests) per second, as far as I understand their pricing. I don't know how this apply to established socket connections? Does this mean 15 new connections or 15 connections maximum? Because if 15 is maximum, I prefer firebase with 50 concurrent connections for free.
Another request would be step-by-step tutorial or demo app, if you have any time for it. Thanks in advance for any reply.

**Comment by ipepe** [comment]
please message me on my mail github@ipepe.pl
